name: CD

on:
  push branches:
    -main
jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy Files To Server via SSh
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST}}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: '22'
        source: "."
        target: "/home/${{secrets.SERVER_USER}}/task_meneger"
      - name: Execute remote SHH commands
        uses: appleboy/ssh-action@v1.0.3
        key: ${{secrets.SERVER_SSH_KEY}}
        port: '22'
        script: |
          cd /home/${{secrets.SERVER_USER}}/task_meneger
          sudo docker-compose down
          sudo docker-compose up -d --build